# Site Configuration

# Theme, mapped to the directory: ./theme/xxxx
theme: default

# HTML Language setting
lang: "zh-TW"

# Plugins, implemented in ./plugins/PLUGIN_NAME
# Use {{ vars.PLUGIN_NAME }} in the settings below

# The output of the plugin can be used below, e.g., {{vars.MediumFollowersCountPlugin}}
plugins:
  # Automatically fetch Medium follower count
  - MediumFollowersCountPlugin:
      username: zhgchgli
  # Automatically fetch Github repo star count
  - GithubRepoStarsCountPlugin:
      - ZhgChgLi/ZMarkupParser
      - ZhgChgLi/ZReviewTender
      - ZhgChgLi/ZMediumToMarkdown
      - ZhgChgLi/linkyee

# Google Analytics tracking id
google_analytics_id:

# HTML Title
title: "Misaka Sarina (aka Baker Siacone)"

# Avatar image path
avatar: "https://scontent.fhkg3-1.fna.fbcdn.net/v/t39.30808-1/586810731_696001710246949_2420885022762085680_n.jpg?stp=dst-jpg_s480x480_tt6&_nc_cat=110&ccb=1-7&_nc_sid=2d3e12&_nc_ohc=LT6lPZzZ7pAQ7kNvwGEy-fu&_nc_oc=AdkflJlbfbbjfwrpI7o63nTVcqxZ6tspoZGjzv9t9kgajmfUmFeEdumqqqiucdD6eDk&_nc_zt=24&_nc_ht=scontent.fhkg3-1.fna&_nc_gid=459ik59v3kE-4Ysp9BkjdA&oh=00_AfmnMAiu5gXigovet5LGYiDayAPEMTMvpzqidjR8KVqD9Q&oe=6938F969"

# Name section text
name: "Misaka Sarina （aka Baker Siacone）"

# Tagline section text
tagline: >-
    Ianas-Baker C. Siacone aka Misaka Sarina / music producer MAIL2ME:MSarina@siacone.art

# List of links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# text: The displayed text for the link
# title: The url title
# url: The URL of the link
# alt: Alternative text for accessibility
# target: `_blank` opens in a new tab, `_self` opens in the same frame
links:
  - link:
      icon: "fa-brands fa-facebook-f"
      text: "我的FB個人主頁"
      url: "https://www.facebook.com/BakerSiacone/"
      title: "我的FB個人主頁"
      alt: "我的FB個人主頁"
      target: "_blank"
  - link:
      icon: "fa-brands fa-facebook-f"
      text: "我的FB粉專"
      url: "https://www.facebook.com/misakasarina/"
      title: "我的FB粉專"
      alt: "我的FB粉專"
      target: "_blank"
  - link:
      icon: "fa-brands fa-facebook-f"
      text: "我的FB社團"
      url: "https://www.facebook.com/share/g/17WHMr54Qj/"
      title: "我的FB社團"
      alt: "我的FB社團"
      target: "_blank"
  - link:
      icon: "fa-brands fa-instagram"
      text: "我的INS個人主頁"
      url: "https://www.instagram.com/bakersiacone/"
      title: "我的INS個人主頁"
      alt: "我的INS個人主頁"
      target: "_blank"
  - link:
      icon: "fa-brands fa-bluesky"
      text: "我的BLUESKY"
      url: "https://bsky.app/profile/msarina.bluesky.siacone.art"
      title: "我的BLUESKY"
      alt: "我的BLUESKY"
      target: "_blank"
  - link:
      icon: "fa-brands fa-youtube"
      text: "我的YouTube（BAKER）"
      url: "https://www.youtube.com/@BakerSiacone"
      title: "我的YouTube（BAKER）"
      alt: "我的YouTube（BAKER）"
      target: "_blank"
  - link:
      icon: "fa-brands fa-youtube"
      text: "我的YouTube（SARINA-近期規劃中）"
      url: "https://www.youtube.com/@BakerSiacone"
      title: "我的YouTube（SARINA-近期規劃中）"
      alt: "我的YouTube（SARINA-近期規劃中）"
      target: "_blank"


# List of social media links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# title: The url title
# url: The URL of the social media link
# alt: Alternative text for accessibility
# target: _blank opens in a new tab, _self opens in the same frame
socials:
  - social:
      icon: "fa-brands fa-facebook-f"
      url: "https://www.facebook.com/misakasarina/"
      title: "我的FB粉專"
      alt: "我的FB粉專"
      target: "_blank"
  - social:
      icon: "fa-brands fa-instagram"
      url: "https://www.instagram.com/bakersiacone/"
      title: "我的INS個人主頁"
      alt: "我的INS個人主頁"
      target: "_blank"
  - social:
      icon: "fa-brands fa-bluesky"
      url: "https://bsky.app/profile/msarina.bluesky.siacone.art"
      title: "我的BLUESKY"
      alt: "我的BLUESKY"
      target: "_blank"
  - social:
      icon: "fa-brands fa-youtube"
      url: "https://www.youtube.com/@BakerSiacone"
      title: "我的YouTube（SARINA-近期規劃中）"
      alt: "我的YouTube（SARINA-近期規劃中）"
      target: "_blank"
  - social:
      icon: "fa-solid fa-envelope"
      url: "mailto:msarina@siacone.art"
      title: "Email: msarina@siacone.art"
      alt: "msarina@siacone.art"
      target: "_blank"

# Footer text
footer: >
    MISAKA SARINA AKA BAKER SIACONE @ SIACONE ART

# Footer copyright message
# Linkyee is a 100% free, open-source project—feel free to modify the copyright message as you like. :)
copyright: >
  Powered by <a href="https://github.com/ZhgChgLi/linkyee" target="_blank">linkyee</a>
